### PR TITLE
Rename the artifacts/k8s/ directory to artifacts/kubernetes

### PR DESCRIPTION
**Pull request by mscherer**
k8s is not a documented name, nor obvious for people who do not know
this is a shorthand for kubernetes. So I think this doesn't belong to
official examples for now.

### CODE REVIEW

**Comment by goern** [comment]
please do also change the references to these artifacts within the Nulecule file, otherwise you just broke the example ;)

**Comment by mscherer** [comment]
Indeed. Then, what about just simply dropping the prefix from the path and have everything at the root of the example ?

**Comment by goern** [comment]
you can do that, but I think it would result in a good practice to separate artifacts by provider.

**Comment by aweiteka** [comment]
@mscherer are you able to update this PR?

**Comment by goern** [comment]
@mscherer could you rebase/fix your PR?

**Comment by mscherer** [comment]
Done

**Comment by aweiteka** [comment]
LGTM

**Pull request merged**
