### PR TITLE
Updated mariadb-app to be working

### PR DESCRIPTION
**Pull request by bexelbie**
- Added README.md
- Updated Nulecule file to latest requirements
- Deleted unnecessary artifacts that were a copy of the Dockerfile setup
  for fedora/mariadb

### CODE REVIEW

**Comment by bexelbie** [comment]
Note: When this is merged, please set up and automatic build in https://registry.hub.docker.com/repos/projectatomic/ for this Dockerfile

**Comment by goern** [comment]
re the docker hub repo: there it https://registry.hub.docker.com/u/projectatomic/mariadb-centos7-atomicapp/

**Comment by bexelbie** [comment]
@goern re: https://registry.hub.docker.com/u/projectatomic/mariadb-centos7-atomicapp/

Can we rename it projectatomic/mariadb-app to differentiate it from https://github.com/projectatomic/nulecule/tree/master/examples/mysql-centos7-atomicapp ?

**Comment by goern** [comment]
Well, I dont care about CentOS7 or not (even thought I think it give a valuable information) but we should establish some branding by using -atomicapp whenever possible. And the main differentiator between `mariadb` and `mysql` Atomic Apps seems to be exactly that, the string `mariadb` or `mysql`

**Comment by bexelbie** [comment]
If we want to create some branding with -atomicapp, that is great.  I am pushing for us to be consistent though:

projectatomic/XXX-atomicap should map to nulecule/examples/XXX

If you want to change the builds, I can push a change to update all the atomic commands.

**Pull request merged**
