### PR TITLE
Update maintainers list

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by cdrage** [comment]
ping @kadel @rtnpro @dustymabe @goern @vpavlin @aweiteka @tradej @veillard

**Comment by LalatenduMohanty** [comment]
Ideally we should not directly remove the old maintainers. We should have something like this https://github.com/gluster/glusterfs/blob/master/MAINTAINERS#L304 . Basically we should be thankful to the old maintainers.

**Comment by rtnpro** [comment]
LGTM :+1:

**Comment by dustymabe** [comment]
I like @LalatenduMohanty's suggestion.

**Comment by bexelbie** [comment]
+1 for PR and @LalatenduMohanty suggestion

**Comment by goern** [comment]
I'm happy to merge this one, when back in office next week and when updated and when we are clear what the direction of Nulecule and other initiatives is.

**Comment by tradej** [comment]
I don't have a problem with being removed from the list per se, but as others have said, Lala's proposition is a nice one.

**Comment by cdrage** [comment]
Thanks @LalatenduMohanty for the suggestion.

I've updated the maintainers list! :) @goern @dustymabe @tradej

**Comment by kadel** [comment]
:+1:

**Comment by cdrage** [comment]
@goern @dustymabe @tradej @vpavlin are you good with this?

**Pull request merged**
