### PR TITLE
Atomicapp storage

### PR DESCRIPTION
**Pull request by goern**
This will define requests for persistent storage for applications, Atomicapp with OpenShift provider may implement it like this: https://gist.github.com/goern/3fb768c88d8d1064460e

### CODE REVIEW

**Comment by aweiteka** [comment]
This is a good pattern to include. I think we're going to merge the 'openshift' branch with master then we can merge this with that approach.

**Comment by goern** [comment]
+1

**Comment by aweiteka** [comment]
@goern I rebased openshift onto master. Please fix conflicts and I'll merge.

**Comment by goern** [comment]
should be resolved...

**Comment by aweiteka** [comment]
Sorry, the current approach is yaml-based without a "graph". Can you make the README edits and proposed file conform to [this example](https://github.com/aweiteka/containerapp-spec/blob/master/spec/v1-alpha/examples/ruby/template.yaml)?

**Pull request merged**
