### PR TITLE
update guestbook-go and redis-centos7 atomicapps for v1

### PR DESCRIPTION
**Pull request by jasonbrooks**

### CODE REVIEW

**Comment by goern** [comment]
LGTM, but.. why you changed from "name" to "app" ?

**Comment by jasonbrooks** [comment]
I followed the upstream there.

**Comment by goern** [comment]
oh :)

**Comment by vpavlin** [comment]
I haven't been able to run it due to some trouble with my Vagrant box:/ Anyway, LGTM and @goern also sent me output from his machine which looks good too.

**Pull request merged**
