### PR TITLE
Remove examples to nulecule-library

### LINKED ISSUE #194: Examples should be removed
With nulecule-library created, the examples dir here should be removed and instead pointed to github.com/projectatomic/nulecule-library

hub.docker.com should sync with any PRs / changes to projectatomic/nulecule-library instead of the current examples directory here.

### PR DESCRIPTION
**Pull request by cdrage**
Removing the current examples and referencing nulecule-library instead.

Fixes #194

### CODE REVIEW

**Comment by cdrage** [comment]
ping @goern @vpavlin @aweiteka

**Comment by dustymabe** [comment]
LGTM

**Comment by aweiteka** [comment]
LGTM. We just need an ack from @vpavlin or @goern

**Comment by cdrage** [comment]
Rebased.

Timeout...

Pinging @vpavlin and @goern  again

**Comment by dustymabe** [comment]
@cdrage - I think the `Add XPathing to spec` commit shouldn't be in this.

**Comment by cdrage** [comment]
Don't know how the hell that was included considering I re-based against upstream master >.>

Fetched and rebased again.

**Comment by dustymabe** [comment]
LGTM

**Pull request merged**
