### PR TITLE
Updated read me to include high level goals

### PR DESCRIPTION
**Pull request by michaelvirgil**

### CODE REVIEW

**Comment by aweiteka** [comment]
LGTM

**Comment by aweiteka** [comment]
@vpavlin this is a good point. It's an important part of the story but maybe not core to the spec.

@michaelvirgil maybe it could be reworded to suggest this use case but not call out that the spec actually defines these modes?

**Comment by michaelvirgil** [comment]
My understanding was that the parameters under the graph section could be used and an optional answer file could be created. It is something that is important for the tool implementation, but facilitated through the spec... is that correct?

**Comment by vpavlin** [comment]
It's probably more complicated:
1. Param has to be specified in Nulecule so that it can be set
2. Param can have default value - which means the value does not have to be provided by deployer
3. If param does not have a default value, it has to be provided by deployer in answers
4. Even if the param has a default value it can be overwritten in answers
5. Based on implementation the answers can be a file, a content of rest api call, an interactively created set of values....

This is why I don't think saying anything about deployment modes makes sense in the spec (maybe a suggestion in implementation guide..)

**Comment by michaelvirgil** [comment]
Got it - agree - I'll remove the line - thanks.

**Comment by aweiteka** [comment]
@vpavlin or @goern please ack

**Pull request merged**
