### PR TITLE
Added Nulecule example for sentry.

### PR DESCRIPTION
**Pull request by rtnpro**
This adds Nulecule example for Sentry on `kubernetes` provider.

### CODE REVIEW

**Comment by vpavlin** [comment]
Please see my comment here: https://github.com/projectatomic/nulecule/pull/165#issuecomment-139237272

**Comment by rtnpro** [comment]
@vpavlin Okies

**Comment by rtnpro** [comment]
@vpavlin added params in Nulecule file, with default values.

**Comment by vpavlin** [comment]
@rtnpro Problem with this, as I noted on irc, is that we probably cannot add this as it does not comply to the current spec - see https://github.com/projectatomic/nulecule/tree/master/spec#schema - there is no `params` object.

@goern Thoughts?:-)

**Comment by goern** [comment]
please relocate this example to https://github.com/projectatomic/nulecule-library

**Pull request closed without merging**
