### PR TITLE
Allow global params in Nulecule spec.

### PR DESCRIPTION
**Pull request by rtnpro**
Adds support for global params in Nulecule spec to support https://github.com/projectatomic/atomicapp/issues/378

### CODE REVIEW

**Comment by aweiteka** [comment]
It's significant to add another top-level element but I understand the rationale. Referencing the existing params object is nice and clean.

For background discussion see https://github.com/projectatomic/atomicapp/issues/378, specifically https://github.com/projectatomic/atomicapp/issues/378#issuecomment-166639255

LGTM

**Comment by cdrage** [comment]
I agree with @rtnpro the rational for global params brings a much cleaner slate to Nulecule.

We can have _both_. Having global params certainly helps bring minimalism to the table. 

This LGTM. Let's get this in! :+1:

**Comment by goern** [comment]
I'm offline today and will revisited it tomorrow

## 

Principal Software Engineer - Systems Design & Engineering
Mobile: +49 171 2801345

Red Hat GmbH, http://www.de.redhat.com/, Sitz: Grasbrunn,
Handelsregister: Amtsgericht München, HRB 153243,
Geschäftsführer: Paul Argiry, Charles Cachera, Michael Cunningham, Michael
O'Neill

**Comment by dustymabe** [comment]
LGTM, let's get this in unless we get feedback from christoph that points otherwise.

**Pull request merged**
