### PR TITLE
Add Glossary to README

### PR DESCRIPTION
**Pull request by johnmark**
Please check glossary for errors

### CODE REVIEW

**Comment by johnmark** [comment]
Re: aggregation - we wanted to define terms that would be useful for the Nulecule context, even if it's "below the spec" or not defined in the spec. It's still useful to define and know - sounds like we can amend the definition to be clear that it's not Nulecule-specific.

**Comment by johnmark** [comment]
Adding @michaelvirgil

**Comment by michaelvirgil** [comment]
I just saw this, also created a request to add the Glossary. Made some changes from the draft and updated the draft to simplify the text. I think in some cases we were being too verbose...

https://github.com/michaelvirgil/nulecule/commit/8abdb74990542ccb01de2a0f4079c5e8559e3c38

What do you think?

**Comment by johnmark** [comment]
+1 from me

**Comment by johnmark** [comment]
superseded by #50

**Pull request closed without merging**
