### PR TITLE
Make schemata Draft 4-compatible

### PR DESCRIPTION
**Pull request by tradej**
Hi, all.

I have fixed the schemata to be compatible with the JSON Schema Draft 4. In addition, I have also removed the "compose" script as it is not needed (the JSON Schema draft has well-defined referencing, which doesn't require that the schema be squashed into one file).

### CODE REVIEW

**Comment by goern** [comment]
no obvious issues, LGTM

**Comment by aweiteka** [comment]
@tradej could you provide a pointer or example how the spec would be concatenated?

Also, `compose.py` was the target script referenced here https://github.com/projectatomic/nulecule/issues/32. I think some of the code should be retained but I haven't looked at it yet.

**Comment by tradej** [comment]
@aweiteka Do we absolutely need to concatenate the schema? The JSON Schema format defines referencing via URIs, so any library that works with JSON Schema must be able to resolve these.

**Comment by aweiteka** [comment]
@tradej no, I'm sure we can work with the standard.

**Comment by vpavlin** [comment]
@tradej One question - can we add something like `doc_text` into the schema so that we can easily generate the human readable version of the spec from it?

**Comment by tradej** [comment]
@vpavlin I would assume that we can. The Python implementation (`python-jsonschema`) ignores unknown keys in the schema gracefully. I'll dig into the official JSON Schema documentation and report with more accurate results.

**Pull request merged**
